# Generated by Django 5.0 on 2026-02-09 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DOCUMENT_UPLOAD", "Document uploadé"),
                            ("DOCUMENT_APPROVE", "Document approuvé"),
                            ("DOCUMENT_REJECT", "Document rejeté"),
                            ("DOCUMENT_DELETE", "Document supprimé"),
                            ("DOCUMENT_UPDATE", "Document modifié"),
                            ("DOCUMENT_DOWNLOAD", "Document téléchargé"),
                            ("USER_CREATE", "Utilisateur créé"),
                            ("USER_UPDATE", "Utilisateur modifié"),
                            ("USER_DELETE", "Utilisateur supprimé"),
                            ("USER_LOGIN", "Connexion utilisateur"),
                            ("USER_LOGOUT", "Déconnexion utilisateur"),
                            ("USER_PASSWORD_CHANGE", "Mot de passe modifié"),
                            ("ADMIN_DEPARTMENT_CREATE", "Département créé"),
                            ("ADMIN_DEPARTMENT_UPDATE", "Département modifié"),
                            ("ADMIN_DEPARTMENT_DELETE", "Département supprimé"),
                            ("ADMIN_ROUTING_RULE_CREATE", "Règle de routage créée"),
                            ("ADMIN_ROUTING_RULE_UPDATE", "Règle de routage modifiée"),
                            ("ADMIN_ROUTING_RULE_DELETE", "Règle de routage supprimée"),
                            (
                                "ADMIN_FILE_TYPE_CONFIG",
                                "Configuration type fichier modifiée",
                            ),
                            ("SECURITY_PERMISSION_DENIED", "Accès refusé"),
                            ("SECURITY_SUSPICIOUS_ACTIVITY", "Activité suspecte"),
                            ("SECURITY_FAILED_LOGIN", "Connexion échouée"),
                            ("SYSTEM_ERROR", "Erreur système"),
                            ("SYSTEM_BACKUP", "Sauvegarde effectuée"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Avertissement"),
                            ("ERROR", "Erreur"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionnaire des changements {champ: [avant, après]}",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_logs_actor_i_3b0e80_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_logs_action_bcaa71_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_logs_created_262184_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="audit_logs_severit_fc52cc_idx"
                    ),
                ],
            },
        ),
    ]
