# Generated by Django 4.2 on 2026-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
