# Generated by Django 5.0 on 2026-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("DOCUMENT_UPLOADED", "Document uploadé"),
                    ("DOCUMENT_OPENED", "Document ouvert"),
                    ("DOCUMENT_APPROVED", "Document approuvé"),
                    ("DOCUMENT_REJECTED", "Document rejeté"),
                    ("DOCUMENT_DELETED", "Document supprimé"),
                    ("VALIDATION", "Document validé"),
                    ("COMMENT", "Nouveau commentaire"),
                    ("ROUTING", "Document routé"),
                    ("SYSTEM", "Notification système"),
                ],
                max_length=20,
            ),
        ),
    ]
