# Generated by Django 4.2 on 2026-02-23 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_refactor_models_realtime"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0004_alter_notification_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-app seulement"),
                            ("EMAIL", "Email seulement"),
                            ("BOTH", "In-app + Email"),
                            ("NONE", "Aucun"),
                        ],
                        default="IN_APP",
                        max_length=10,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immédiat"),
                            ("DIGEST_HOURLY", "Résumé hourly"),
                            ("DIGEST_DAILY", "Résumé quotidien"),
                            ("DIGEST_WEEKLY", "Résumé hebdo"),
                            ("NEVER", "Jamais"),
                        ],
                        default="IMMEDIATE",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                (
                    "quiet_start",
                    models.TimeField(
                        default="22:00", help_text="Pas de notifications de 22h à..."
                    ),
                ),
                ("quiet_end", models.TimeField(default="08:00", help_text="...à 8h")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Preference",
                "db_table": "notification_preferences",
            },
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_created_e4c995_idx",
        ),
        migrations.AddField(
            model_name="notification",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Auto-delete après cette date", null=True
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="group_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Pour grouper les notifications similaires",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extra data (actor, reason, etc)"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Basse"),
                    ("NORMAL", "Normal"),
                    ("HIGH", "Haute"),
                    ("URGENT", "Urgent"),
                ],
                default="NORMAL",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="documents.document",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("DOCUMENT_UPLOADED", "Document uploadé"),
                    ("DOCUMENT_OPENED", "Document ouvert"),
                    ("DOCUMENT_APPROVED", "Document approuvé"),
                    ("DOCUMENT_REJECTED", "Document rejeté"),
                    ("DOCUMENT_DELETED", "Document supprimé"),
                    ("VALIDATION", "Document validé"),
                    ("COMMENT", "Nouveau commentaire"),
                    ("ROUTING", "Document routé"),
                    ("SYSTEM", "Notification système"),
                    ("MENTION", "Vous avez été mentionné"),
                    ("SHARE", "Document partagé"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_archived"],
                name="notificatio_recipie_d51e24_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "created_at"],
                name="notificatio_recipie_2c3905_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["group_key", "created_at"],
                name="notificatio_group_k_d7f6c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority", "created_at"], name="notificatio_priorit_22e6c2_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["user"], name="notificatio_user_id_553b46_idx"),
        ),
    ]
