# Generated by Django 4.2 on 2026-02-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0007_alter_folder_folder_type"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pole",
            field=models.ForeignKey(
                blank=True,
                help_text="Pôle de l'utilisateur (si POLE_MANAGER)",
                limit_choices_to={"folder_type": "pole"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pole_users",
                to="folders.folder",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("AGENT", "Agent"),
                    ("ADMIN", "Administrateur"),
                    ("POLE_MANAGER", "Gestionnaire Pôle"),
                    ("FILIALE_MANAGER", "Gestionnaire Filiale"),
                    ("SERVICE_MANAGER", "Gestionnaire Service"),
                    ("DOCUMENT_MANAGER", "Gestionnaire Document (Re-routing)"),
                ],
                default="AGENT",
                max_length=20,
            ),
        ),
    ]
