# Generated by Django 4.2 on 2026-02-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0008_add_system_folders_support"),
        ("users", "0003_remove_legacy_branch_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Filiale de l'utilisateur",
                limit_choices_to={"folder_type": "filiale"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_users",
                to="folders.folder",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Service (département) de l'utilisateur",
                limit_choices_to={"folder_type": "service"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_users",
                to="folders.folder",
            ),
        ),
    ]
