# Generated by Django 5.0 on 2026-01-22 07:59

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("folders", "__first__"),
        ("routing_rules", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=30, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "allowed_formats",
                    models.CharField(
                        default="pdf,docx",
                        help_text="Formats autorisés séparés par des virgules (ex: pdf,xlsx,docx)",
                        max_length=255,
                    ),
                ),
                ("requires_excel", models.BooleanField(default=False)),
                (
                    "excel_sheet_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom de la feuille Excel requise",
                        max_length=100,
                    ),
                ),
                (
                    "required_columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des colonnes requises en JSON: ['Colonne1', 'Colonne2']",
                    ),
                ),
                ("max_file_size_mb", models.IntegerField(default=50)),
                (
                    "max_rows",
                    models.IntegerField(
                        blank=True,
                        default=100000,
                        help_text="Pour les fichiers Excel",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_validation", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spécification de document",
                "verbose_name_plural": "Spécifications de documents",
                "db_table": "document_specifications",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONGE", "Demande de congé"),
                            ("MEDICAL", "Certificat médical"),
                            ("RAPPORT", "Rapport d'activité"),
                            ("TEMPS", "Fiche de temps"),
                            ("FORMATION", "Demande de formation"),
                            ("ADMINISTRATIF", "Document administratif"),
                            ("JUSTIFICATIF", "Justificatif"),
                            ("CONTRAT", "Contrat"),
                            ("EVALUATION", "Évaluation"),
                            ("DONNEES_EXCEL", "Données Excel"),
                            ("DONNEES_AGENTS", "Données des agents"),
                            ("DONNEES_PROJETS", "Données des projets"),
                            ("DONNEES_HEURES", "Données des heures"),
                            ("DONNEES_ABSENCES", "Données des absences"),
                            ("EXPORT_EXCEL", "Export Excel"),
                            ("RAPPORT_EXCEL", "Rapport Excel"),
                            ("RAPPORT_MENSUEL", "Rapport mensuel Excel"),
                            ("RAPPORT_ANNUEL", "Rapport annuel Excel"),
                            ("STATISTIQUES_EXCEL", "Statistiques Excel"),
                            ("BULLETINS_PAIE", "Bulletins de paie Excel"),
                            ("FEUILLE_PAIE", "Feuille de paie"),
                            ("CHARGES_SOCIALES", "Charges sociales"),
                            ("DECLARATIONS_URSSAF", "Déclarations URSSAF"),
                            ("BUDGET_PREVISIONNEL", "Budget prévisionnel"),
                            ("BUDGET_REALISE", "Budget réalisé"),
                            ("FACTURES_EXCEL", "Factures"),
                            ("DEVIS_EXCEL", "Devis"),
                            ("DEPENSES_EXCEL", "Dépenses"),
                            ("PLANNING_EXCEL", "Planning"),
                            ("CALENDRIER_FORMATION", "Calendrier de formation"),
                            ("CALENDRIER_CONGES", "Calendrier des congés"),
                            ("CALENDRIER_PROJETS", "Calendrier des projets"),
                            ("INVENTAIRE_EXCEL", "Inventaire"),
                            ("NOMENCLATURE", "Nomenclature"),
                            ("REFERENTIELS", "Référentiels"),
                            ("IMPORTS_DONNEES", "Imports de données"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOUVEAU", "Nouveau"),
                            ("VALIDATION_EN_COURS", "Validation en cours"),
                            ("EN_ATTENTE", "En attente"),
                            ("EN_COURS", "En cours"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        default="NOUVEAU",
                        max_length=20,
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("file_size", models.IntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_format", models.CharField(blank=True, max_length=20)),
                ("excel_sheet_name", models.CharField(blank=True, max_length=100)),
                ("excel_row_count", models.IntegerField(default=0)),
                ("excel_column_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("routed_automatically", models.BooleanField(default=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="folders.folder",
                    ),
                ),
                (
                    "routing_rule_applied",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="routing_rules.routingrule",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documentspecification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Validé"),
                            ("FAILED", "Échoué"),
                            ("WARNING", "Avertissement"),
                        ],
                        max_length=10,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("validation_details", models.JSONField(blank=True, default=dict)),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_result",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat de validation",
                "verbose_name_plural": "Résultats de validation",
                "db_table": "document_validation_results",
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["agent", "status"], name="documents_agent_i_7be503_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type", "created_at"],
                name="documents_documen_0d20f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["folder", "status"], name="documents_folder__8cd630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_validated", "status"], name="documents_is_vali_998b0a_idx"
            ),
        ),
    ]
