# Generated by Django 4.2 on 2026-02-23 08:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routing_rules", "0001_initial"),
        ("folders", "0007_alter_folder_folder_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("REPORT", "Rapport"),
                            ("LETTER", "Lettre"),
                            ("REQUEST", "Demande"),
                            ("CONTRACT", "Contrat"),
                            ("PROCEDURE", "Procédure"),
                            ("FORM", "Formulaire"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="templates/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "docx",
                                    "xlsx",
                                    "pptx",
                                    "doc",
                                    "xls",
                                    "ppt",
                                ]
                            )
                        ],
                    ),
                ),
                ("file_size", models.BigIntegerField(default=0, editable=False)),
                (
                    "file_type",
                    models.CharField(default="DOC", editable=False, max_length=20),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("ALL", "Tous les agents"),
                            ("DEPARTMENT", "Par département"),
                            ("CUSTOM", "Agents sélectionnés"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("downloads_count", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=1)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileTypeConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "Word (.doc)"),
                            ("docx", "Word (.docx)"),
                            ("txt", "Texte (.txt)"),
                            ("xlsx", "Excel (.xlsx) - Moderne"),
                            ("xlsm", "Excel Macro (.xlsm)"),
                            ("xltx", "Template Excel (.xltx)"),
                            ("xltm", "Template Excel Macro (.xltm)"),
                            ("xls", "Excel (.xls) - Ancien"),
                            ("xlt", "Template Excel ancien (.xlt)"),
                            ("xlsb", "Excel Binaire (.xlsb)"),
                            ("xlam", "Add-in Excel (.xlam)"),
                            ("csv", "CSV (Données délimitées)"),
                            ("tsv", "TSV (Tab délimité)"),
                            ("ods", "OpenDocument Spreadsheet (.ods)"),
                            ("image", "Image (JPG, PNG, etc.)"),
                            ("zip", "Archive (ZIP)"),
                        ],
                        help_text="Type de fichier (extension)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nom d'affichage du type de fichier", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description du type de fichier"
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Taille maximale du fichier en MB",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "min_file_size_kb",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Taille minimale du fichier en KB",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_rows",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre maximum de lignes (pour les feuilles de calcul)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                (
                    "max_columns",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre maximum de colonnes (pour les feuilles de calcul)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(16384),
                        ],
                    ),
                ),
                (
                    "max_sheets",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre maximum de feuilles (pour les classeurs)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_pages",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre maximum de pages (pour les documents)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_width_px",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Largeur maximale en pixels (pour les images)",
                        null=True,
                    ),
                ),
                (
                    "max_height_px",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hauteur maximale en pixels (pour les images)",
                        null=True,
                    ),
                ),
                (
                    "min_width_px",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Largeur minimale en pixels (pour les images)",
                        null=True,
                    ),
                ),
                (
                    "min_height_px",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hauteur minimale en pixels (pour les images)",
                        null=True,
                    ),
                ),
                (
                    "require_macros_disabled",
                    models.BooleanField(
                        default=False, help_text="Les macros doivent être désactivées"
                    ),
                ),
                (
                    "require_no_password",
                    models.BooleanField(
                        default=False,
                        help_text="Le fichier ne doit pas être protégé par mot de passe",
                    ),
                ),
                (
                    "allow_external_links",
                    models.BooleanField(
                        default=True, help_text="Les liens externes sont autorisés"
                    ),
                ),
                (
                    "require_utf8_encoding",
                    models.BooleanField(
                        default=False, help_text="L'encodage UTF-8 est obligatoire"
                    ),
                ),
                (
                    "allowed_sheets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des noms de feuilles autorisées (vide = toutes autorisées)",
                    ),
                ),
                (
                    "forbidden_columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Colonnes interdites par nom ou index",
                    ),
                ),
                (
                    "required_columns",
                    models.JSONField(
                        blank=True, default=list, help_text="Colonnes obligatoires"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Ce type de fichier est accepté"
                    ),
                ),
                (
                    "is_auto_validated",
                    models.BooleanField(
                        default=True,
                        help_text="Valider automatiquement lors de l'upload",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration Type Fichier",
                "verbose_name_plural": "Configurations Types Fichiers",
                "db_table": "file_type_configurations",
                "ordering": ["file_type"],
            },
        ),
        migrations.CreateModel(
            name="FileTypeRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Taille max pour cette combinaison (remplace la config générale si défini)",
                        null=True,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Ce type de fichier est obligatoire pour cette règle (au moins un parmi les required)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exigence Type Fichier",
                "verbose_name_plural": "Exigences Types Fichiers",
                "db_table": "file_type_requirements",
                "ordering": ["routing_rule", "file_type_config"],
            },
        ),
        migrations.CreateModel(
            name="TemplateDownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("file", models.FileField(upload_to="template_versions/%Y/%m/%d/")),
                ("changelog", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.RemoveIndex(
            model_name="document",
            name="documents_is_vali_998b0a_idx",
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_validated",
        ),
        migrations.RemoveField(
            model_name="document",
            name="validated_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="validated_by",
        ),
        migrations.AddField(
            model_name="document",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("FACTURE", "Facture"),
                    ("BON_COMMANDE", "Bon de Commande"),
                    ("CONTRAT", "Contrat"),
                    ("RAPPORT", "Rapport"),
                    ("CONGE", "Demande de congé"),
                    ("NOTE_FRAIS", "Note de frais"),
                    ("MEDICAL", "Certificat médical"),
                    ("TEMPS", "Fiche de temps"),
                    ("FORMATION", "Demande de formation"),
                    ("ADMINISTRATIF", "Document administratif"),
                    ("JUSTIFICATIF", "Justificatif"),
                    ("EVALUATION", "Évaluation"),
                    ("BUDGET", "Budget"),
                    ("DEMANDE", "Demande"),
                    ("ATTESTATION", "Attestation"),
                    ("DONNEES_EXCEL", "Données Excel"),
                    ("DONNEES_AGENTS", "Données des agents"),
                    ("DONNEES_PROJETS", "Données des projets"),
                    ("DONNEES_HEURES", "Données des heures"),
                    ("DONNEES_ABSENCES", "Données des absences"),
                    ("EXPORT_EXCEL", "Export Excel"),
                    ("RAPPORT_EXCEL", "Rapport Excel"),
                    ("RAPPORT_MENSUEL", "Rapport mensuel Excel"),
                    ("RAPPORT_ANNUEL", "Rapport annuel Excel"),
                    ("STATISTIQUES_EXCEL", "Statistiques Excel"),
                    ("BULLETINS_PAIE", "Bulletins de paie Excel"),
                    ("FEUILLE_PAIE", "Feuille de paie"),
                    ("CHARGES_SOCIALES", "Charges sociales"),
                    ("DECLARATIONS_URSSAF", "Déclarations URSSAF"),
                    ("BUDGET_PREVISIONNEL", "Budget prévisionnel"),
                    ("BUDGET_REALISE", "Budget réalisé"),
                    ("FACTURES_EXCEL", "Factures"),
                    ("DEVIS_EXCEL", "Devis"),
                    ("DEPENSES_EXCEL", "Dépenses"),
                    ("PLANNING_EXCEL", "Planning"),
                    ("CALENDRIER_FORMATION", "Calendrier de formation"),
                    ("CALENDRIER_CONGES", "Calendrier des congés"),
                    ("CALENDRIER_PROJETS", "Calendrier des projets"),
                    ("INVENTAIRE_EXCEL", "Inventaire"),
                    ("NOMENCLATURE", "Nomenclature"),
                    ("REFERENTIELS", "Référentiels"),
                    ("IMPORTS_DONNEES", "Imports de données"),
                    ("AUTRE", "Autre"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOUVEAU", "Nouveau"),
                    ("EN_COURS", "En cours de révision"),
                    ("VALIDE", "Validé"),
                    ("REJETE", "Rejeté"),
                    ("ARCHIVE", "Archivé"),
                ],
                default="NOUVEAU",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentspecification",
            name="allowed_formats",
            field=models.CharField(
                default="pdf,docx",
                help_text="Formats autorisés séparés par des virgules (ex: pdf,xlsx,xlsm,xls,csv)",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "created_at"], name="documents_status_497c5a_idx"
            ),
        ),
        migrations.AddField(
            model_name="templateversion",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templateversion",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="documents.documenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="templatedownloadlog",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_logs",
                to="documents.documenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="templatedownloadlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_downloads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filetyperequirement",
            name="file_type_config",
            field=models.ForeignKey(
                help_text="Type de fichier autorisé pour cette règle",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routing_requirements",
                to="documents.filetypeconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="filetyperequirement",
            name="routing_rule",
            field=models.ForeignKey(
                help_text="Règle de routage associée",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_type_requirements",
                to="routing_rules.routingrule",
            ),
        ),
        migrations.AddField(
            model_name="filetypeconfiguration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_file_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Services (départements) autorisés à accéder à ce template",
                limit_choices_to={"folder_type": "service"},
                related_name="template_access",
                to="folders.folder",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templateversion",
            unique_together={("template", "version_number")},
        ),
        migrations.AlterUniqueTogether(
            name="filetyperequirement",
            unique_together={("routing_rule", "file_type_config")},
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="documents_d_created_d8e05e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["visibility", "is_active"],
                name="documents_d_visibil_16ceee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["template_type"], name="documents_d_templat_02b3bb_idx"
            ),
        ),
    ]
