# Generated by Django 4.2 on 2026-02-23 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0007_alter_folder_folder_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0002_documenttemplate_filetypeconfiguration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("AUTO_ROUTING", "Routage automatique"),
                            ("MANUAL_TRANSFER", "Transfer manuel"),
                            ("CROSS_POLE", "Transfer entre Pôles"),
                            ("CROSS_FILIALE", "Transfer entre Filiales"),
                            ("CROSS_SERVICE", "Transfer entre Services"),
                            ("COMPLIANCE_MOVE", "Mouvement pour conformité"),
                            ("OTHER", "Autre raison"),
                        ],
                        default="MANUAL_TRANSFER",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("transferred_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document transféré",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="documents.document",
                    ),
                ),
                (
                    "from_folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dossier d'origine",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_from",
                        to="folders.folder",
                    ),
                ),
                (
                    "to_folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dossier de destination",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_to",
                        to="folders.folder",
                    ),
                ),
                (
                    "transferred_by",
                    models.ForeignKey(
                        help_text="Utilisateur qui a effectué le transfer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer de document",
                "verbose_name_plural": "Transfers de documents",
                "db_table": "document_transfers",
                "ordering": ["-transferred_at"],
            },
        ),
    ]
