# Generated by Django 4.2 on 2026-02-23 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0003_add_document_transfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("VIEW", "Lecture seule"),
                            ("COMMENT", "Lecture + Commentaires"),
                            ("DOWNLOAD", "Téléchargement"),
                            ("EDIT", "Édition"),
                            ("SHARE", "Can re-share"),
                        ],
                        default="VIEW",
                        help_text="Niveau de permission",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Message personnel avec le partage"
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="La date d'expiration du partage (vide = pas d'expiration)",
                        null=True,
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Dernière fois que le destinataire a accédé au document",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document partagé",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="documents.document",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        help_text="Utilisateur qui partage le document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_shared_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        help_text="Utilisateur qui reçoit le document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_shared_with_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partage de document",
                "verbose_name_plural": "Partages de documents",
                "db_table": "document_shares",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentshare",
            index=models.Index(
                fields=["shared_with", "-shared_at"],
                name="document_sh_shared__bb7307_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentshare",
            index=models.Index(
                fields=["shared_by"], name="document_sh_shared__fff59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentshare",
            index=models.Index(
                fields=["document"], name="document_sh_documen_bc141e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentshare",
            unique_together={("document", "shared_by", "shared_with")},
        ),
    ]
