# Generated by Django 4.2 on 2026-02-23 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_add_document_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(
                help_text="Document title (3-255 characters)",
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
