# Generated by Django 4.2 on 2026-02-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_documentshare_folder_sharing"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentshare",
            new_name="document_sh_shared__e50441_idx",
            old_name="documents_d_shared_idx",
        ),
        migrations.RenameIndex(
            model_name="documentshare",
            new_name="document_sh_share_t_45ef12_idx",
            old_name="documents_d_type_idx",
        ),
    ]
