# Generated by Django 4.2 on 2026-02-25 11:09

from django.db import migrations, models
import django.db.models.deletion


def create_document_types(apps, schema_editor):
    """Créer les types de documents par défaut."""
    DocumentType = apps.get_model("documents", "DocumentType")

    defaults = [
        {
            "name": "FACTURE",
            "display_name": "Facture",
            "icon": "file-text",
            "color": "#10B981",
        },
        {
            "name": "BON_COMMANDE",
            "display_name": "Bon de Commande",
            "icon": "shopping-cart",
            "color": "#3B82F6",
        },
        {
            "name": "CONTRAT",
            "display_name": "Contrat",
            "icon": "file",
            "color": "#8B5CF6",
        },
        {
            "name": "RAPPORT",
            "display_name": "Rapport",
            "icon": "bar-chart-2",
            "color": "#F59E0B",
        },
        {
            "name": "CONGE",
            "display_name": "Demande de congé",
            "icon": "calendar",
            "color": "#EF4444",
        },
        {
            "name": "NOTE_FRAIS",
            "display_name": "Note de frais",
            "icon": "credit-card",
            "color": "#06B6D4",
        },
        {
            "name": "MEDICAL",
            "display_name": "Certificat médical",
            "icon": "heart",
            "color": "#EC4899",
        },
        {
            "name": "TEMPS",
            "display_name": "Fiche de temps",
            "icon": "clock",
            "color": "#14B8A6",
        },
        {
            "name": "FORMATION",
            "display_name": "Demande de formation",
            "icon": "book",
            "color": "#F97316",
        },
        {
            "name": "ADMINISTRATIF",
            "display_name": "Document administratif",
            "icon": "file-text",
            "color": "#6B7280",
        },
        {
            "name": "JUSTIFICATIF",
            "display_name": "Justificatif",
            "icon": "check-circle",
            "color": "#10B981",
        },
        {
            "name": "EVALUATION",
            "display_name": "Évaluation",
            "icon": "star",
            "color": "#FBBF24",
        },
        {
            "name": "BUDGET",
            "display_name": "Budget",
            "icon": "pie-chart",
            "color": "#3B82F6",
        },
        {
            "name": "DEMANDE",
            "display_name": "Demande",
            "icon": "inbox",
            "color": "#8B5CF6",
        },
        {
            "name": "ATTESTATION",
            "display_name": "Attestation",
            "icon": "award",
            "color": "#10B981",
        },
        {
            "name": "DONNEES_EXCEL",
            "display_name": "Données Excel",
            "icon": "table",
            "color": "#059669",
        },
        {
            "name": "DONNEES_AGENTS",
            "display_name": "Données des agents",
            "icon": "users",
            "color": "#0891B2",
        },
        {
            "name": "DONNEES_PROJETS",
            "display_name": "Données des projets",
            "icon": "briefcase",
            "color": "#7C3AED",
        },
        {
            "name": "DONNEES_HEURES",
            "display_name": "Données des heures",
            "icon": "clock",
            "color": "#DC2626",
        },
        {
            "name": "DONNEES_ABSENCES",
            "display_name": "Données des absences",
            "icon": "x-circle",
            "color": "#EA580C",
        },
        {
            "name": "RAPPORT_MENSUEL",
            "display_name": "Rapport mensuel",
            "icon": "calendar",
            "color": "#0369A1",
        },
        {
            "name": "RAPPORT_ANNUEL",
            "display_name": "Rapport annuel",
            "icon": "bar-chart-2",
            "color": "#1E40AF",
        },
    ]

    for doc_type in defaults:
        DocumentType.objects.get_or_create(
            name=doc_type["name"],
            defaults={
                "display_name": doc_type["display_name"],
                "icon": doc_type["icon"],
                "color": doc_type["color"],
            },
        )


def migrate_document_types_data(apps, schema_editor):
    """Migrer les anciennes valeurs document_type vers la nouvelle table."""
    Document = apps.get_model("documents", "Document")
    DocumentType = apps.get_model("documents", "DocumentType")

    for doc in Document.objects.filter(document_type_legacy__isnull=False):
        try:
            doc_type_obj = DocumentType.objects.get(name=doc.document_type_legacy)
            doc.document_type = doc_type_obj
            doc.save(update_fields=["document_type"])
        except DocumentType.DoesNotExist:
            # Si le type n'existe pas, créer une nouvelle entrée
            doc_type_obj = DocumentType.objects.create(
                name=doc.document_type_legacy,
                display_name=doc.document_type_legacy.replace("_", " "),
            )
            doc.document_type = doc_type_obj
            doc.save(update_fields=["document_type"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0010_rename_documents_d_shared_idx_document_sh_shared__e50441_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom unique du type de document (ex: Facture, Congé, Rapport)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nom affiché dans l'interface (ex: Demande de congé)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description du type de document"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active ce type de document"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="file",
                        help_text="Icône Lucide (ex: file, file-pdf, file-text)",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#6B7280",
                        help_text="Couleur hex pour l'affichage",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type de document",
                "verbose_name_plural": "Types de documents",
                "db_table": "document_types",
                "ordering": ["display_name"],
            },
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_documen_5feedf_idx",
            old_name="documents_documen_0d20f5_idx",
        ),
        migrations.AddField(
            model_name="document",
            name="document_type_legacy",
            field=models.CharField(
                blank=True,
                help_text="Ancien champ - sera supprimé après migration",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type de document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.documenttype",
            ),
        ),
        # Créer les types par défaut
        migrations.RunPython(create_document_types),
        # Migrer les données existantes
        migrations.RunPython(migrate_document_types_data),
    ]
