# Generated by Django 4.2 on 2026-02-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_documenttype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="allowed_formats",
            field=models.CharField(
                blank=True,
                default="pdf,docx,xlsx",
                help_text="Formats autorisés (séparés par des virgules, ex: pdf,docx,xlsx)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="excel_sheet_name",
            field=models.CharField(
                blank=True,
                help_text="Nom de la feuille Excel à valider",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="max_file_size_mb",
            field=models.IntegerField(
                default=50, help_text="Taille maximale du fichier en MB"
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="max_rows",
            field=models.IntegerField(
                blank=True, help_text="Nombre maximum de lignes pour Excel", null=True
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="required_columns",
            field=models.TextField(
                blank=True,
                help_text="Colonnes requises pour Excel (séparées par des virgules)",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="requires_excel",
            field=models.BooleanField(
                default=False, help_text="Ce type nécessite une validation Excel"
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="requires_validation",
            field=models.BooleanField(
                default=True, help_text="La validation est requise pour ce type"
            ),
        ),
    ]
