# Generated by Django 4.2 on 2026-02-20 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("folders", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="folder",
            options={
                "ordering": ["folder_type", "name"],
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
            },
        ),
        migrations.AddField(
            model_name="folder",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Code unique (ex: BEN pour Bénin)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="country_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Code ISO-2 (ex: BJ pour Bénin). Unique uniquement pour les branches.",
                max_length=2,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="folder_type",
            field=models.CharField(
                choices=[
                    ("branch", "Filiale"),
                    ("department", "Département"),
                    ("section", "Section"),
                ],
                default="section",
                help_text="Type de dossier: Filiale, Département, ou Section",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="folder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_folders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["parent", "is_active"], name="folder_parent_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["folder_type", "is_active"], name="folder_type_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["code"], name="folder_code_idx"),
        ),
    ]
