# Generated by Django 4.2 on 2026-02-20

from django.db import migrations
from django.utils import timezone


def create_8_poles_7_filiales_structure(apps, schema_editor):
    """
    Créer 8 Pôles (un par type) × 7 Filiales = 56 Filiales
    """
    Folder = apps.get_model('folders', 'Folder')
    
    # Si la table est vide, créer les données d'initialisation
    if Folder.objects.count() == 0:
        branches_data = [
            ("Bénin", "BEN", "BJ"),
            ("Cameroun", "CMR", "CM"),
            ("Congo", "CON", "CG"),
            ("Côte d'Ivoire", "CIV", "CI"),
            ("Guinée", "GUI", "GN"),
            ("Guinée Équatoriale", "GEQ", "GQ"),
            ("Guinée-Bissau", "GUB", "GW"),
        ]
        
        service_types = ["Administration", "Commercial", "Direction", "Finance", "Informatique", "Logistique", "Qualité", "RH"]
        
        print("\n📦 Créer données d'initialisation (7 branches + 8 services/branche)...")
        for name, code, cc in branches_data:
            b = Folder.objects.create(
                name=name, code=code, country_code=cc, parent=None,
                folder_type='branch', created_at=timezone.now(), updated_at=timezone.now()
            )
            for stype in service_types:
                Folder.objects.create(
                    name=stype, code=f"{code}_{stype[:3]}", parent=b,
                    folder_type='department', created_at=timezone.now(), updated_at=timezone.now()
                )
        print(f"  ✅ {Folder.objects.count()} folders créés")
    
    # Récupérer les branches
    branches = list(Folder.objects.filter(
        parent__isnull=True,
        folder_type__in=['branch', 'filiale']
    ).order_by('name'))
    
    if len(branches) != 7:
        print(f"⚠️ Expected 7 branches, found {len(branches)}")
        return
    
    # Identifier les types uniques
    services = Folder.objects.filter(folder_type__in=['service', 'department'])
    service_types = sorted(set(s.name for s in services))
    
    if len(service_types) > 8:
        service_types = service_types[:8]
    
    print(f"\n📊 Restructuration en 8 Pôles × 7 Filiales")
    print(f"  Types trouvés: {service_types}")
    
    # Effacer l'ancienne structure
    Folder.objects.all().delete()
    
    # Créer 8 Pôles
    poles_created = filiales_created = services_created = 0
    
    for type_name in service_types:
        pole = Folder.objects.create(
            name=f"Pôle {type_name}", code=f"POL_{type_name[:3].upper()}",
            parent=None, folder_type='pole', created_at=timezone.now(), updated_at=timezone.now()
        )
        poles_created += 1
        
        for branch in branches:
            filiale_code = f"POL_{type_name[:3].upper()}_{branch.code[-2:].upper()}"
            filiale = Folder.objects.create(
                name=branch.name, code=filiale_code, country_code=branch.country_code,
                parent=pole, folder_type='filiale', created_at=timezone.now(), updated_at=timezone.now()
            )
            filiales_created += 1
            
            # Créer le Service
            service = Folder.objects.create(
                name=type_name, code=f"SRV_{type_name[:3].upper()}_{filiale_code[-2:]}",
                parent=filiale, folder_type='service', created_at=timezone.now(), updated_at=timezone.now()
            )
            services_created += 1
    
    print(f"\n✅ {poles_created} Pôles créés")
    print(f"✅ {filiales_created} Filiales créées ({filiales_created // poles_created} par pôle)")
    print(f"✅ {services_created} Services créés")
    print(f"✅ Total: {Folder.objects.count()} folders")


def reverse_restructure(apps, schema_editor):
    """Reverse - delete all folders"""
    Folder = apps.get_model('folders', 'Folder')
    Folder.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0005_cleanup_folder_types_and_orphan_depts"),
    ]

    operations = [
        migrations.RunPython(create_8_poles_7_filiales_structure, reverse_restructure),
    ]
