# Generated by Django 4.2 on 2026-02-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0006_correct_8_poles_7_filiales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="folder_type",
            field=models.CharField(
                choices=[
                    ("pole", "Pôle"),
                    ("filiale", "Filiale"),
                    ("service", "Service"),
                    ("sub_service", "Sous-service"),
                    ("branch", "Filiale (legacy)"),
                    ("department", "Département (legacy)"),
                    ("section", "Section (legacy)"),
                ],
                default="section",
                help_text="Type de dossier: Filiale, Département, ou Section",
                max_length=20,
            ),
        ),
    ]
