# Generated by Django 4.2 on 2026-02-25 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("folders", "0007_alter_folder_folder_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_system_folder",
            field=models.BooleanField(
                default=False,
                help_text="Dossier système créé automatiquement (ex: Received pour utilisateur)",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Propriétaire du dossier (pour les dossiers personnels comme Received)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_folders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="folder_type",
            field=models.CharField(
                choices=[
                    ("pole", "Pôle"),
                    ("filiale", "Filiale"),
                    ("service", "Service"),
                    ("sub_service", "Sous-service"),
                    ("year", "Année"),
                    ("month", "Mois"),
                    ("received_user", "Reçu par utilisateur"),
                    ("branch", "Filiale (legacy)"),
                    ("department", "Département (legacy)"),
                    ("section", "Section (legacy)"),
                ],
                default="section",
                help_text="Type de dossier: Filiale, Département, ou Section",
                max_length=20,
            ),
        ),
    ]
