# Generated by Django 4.2 on 2026-02-25 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("folders", "0008_add_system_folders_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Titre de l'événement", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Description de l'événement"),
                ),
                (
                    "event_date",
                    models.DateTimeField(help_text="Date et heure de l'événement"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, help_text="Heure de début", null=True),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, help_text="Heure de fin", null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Lieu de l'événement", max_length=255
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, help_text="Visible par tous"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PUBLISHED", "Publié"),
                            ("ARCHIVED", "Archivé"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image de l'événement",
                        null=True,
                        upload_to="events/",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Créateur de l'événement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visible_to_folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si non public, visible seulement à ce dossier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visible_events",
                        to="folders.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "db_table": "events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="EmailSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Sujet de l'email", max_length=255),
                ),
                ("message", models.TextField(help_text="Contenu de l'email")),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("ALL_USERS", "Tous les utilisateurs"),
                            ("POLE", "Pôle spécifique"),
                            ("FILIALE", "Filiale spécifique"),
                            ("SERVICE", "Service spécifique"),
                            ("SUB_SERVICE", "Sous-service spécifique"),
                        ],
                        default="ALL_USERS",
                        help_text="Type de destinataire",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(help_text="Date et heure d'envoi programmée"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SCHEDULED", "Programmé"),
                            ("SENT", "Envoyé"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="Date d'envoi réel", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Message d'erreur si échec"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Utilisateur qui a créé le planning",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_email_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dossier destinataire (si recipient_type != ALL_USERS)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_schedules",
                        to="folders.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programmation d'email",
                "verbose_name_plural": "Programmations d'emails",
                "db_table": "email_schedules",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "event_date"], name="events_status_4e8a13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["created_by"], name="events_created_2c88fa_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_public"], name="events_is_publ_cf11db_idx"),
        ),
        migrations.AddIndex(
            model_name="emailschedule",
            index=models.Index(
                fields=["status", "scheduled_at"], name="email_sched_status_3abc88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailschedule",
            index=models.Index(
                fields=["created_by"], name="email_sched_created_9069a5_idx"
            ),
        ),
    ]
