# Generated by Django 4.2 on 2026-02-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailschedule",
            name="monthly_days",
            field=models.CharField(
                blank=True,
                help_text="Jours du mois pour récurrence (ex: 15,23). Séparés par des virgules",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="emailschedule",
            name="monthly_time",
            field=models.TimeField(
                blank=True,
                help_text="Heure d'envoi pour les emails mensuels",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emailschedule",
            name="recurrence_type",
            field=models.CharField(
                choices=[("ONE_TIME", "Une seule fois"), ("MONTHLY", "Chaque mois")],
                default="ONE_TIME",
                help_text="Type de programmation: une seule fois ou récurrence mensuelle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailschedule",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure d'envoi programmée (pour ONE_TIME)",
                null=True,
            ),
        ),
    ]
