# Generated by Django 5.0 on 2026-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "conditions",
                    models.JSONField(
                        help_text="Format: {'field': 'value', 'operator': 'equals/contains/in'}"
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("times_applied", models.IntegerField(default=0)),
                ("last_applied", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Règle de routage",
                "verbose_name_plural": "Règles de routage",
                "db_table": "routing_rules",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
