# Generated by Django 4.2 on 2026-02-25 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0008_add_system_folders_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "documents",
            "0010_rename_documents_d_shared_idx_document_sh_shared__e50441_idx_and_more",
        ),
        ("routing_rules", "0003_converged_folder_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingrule",
            name="auto_create_hierarchy",
            field=models.BooleanField(
                default=True,
                help_text="Créer automatiquement les dossiers manquants selon le routing_path",
            ),
        ),
        migrations.AddField(
            model_name="routingrule",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Filiale concernée par cette règle (null = s'applique à toutes les filiales)",
                limit_choices_to={"folder_type": "filiale"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routing_rules",
                to="folders.folder",
            ),
        ),
        migrations.AddField(
            model_name="routingrule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routingrule",
            name="destination_folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Dossier fixe de destination (si routing_path non spécifié)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routing_destination_rules",
                to="folders.folder",
            ),
        ),
        migrations.CreateModel(
            name="DepartmentDocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("RH", "Ressources Humaines"),
                            ("IT", "Informatique"),
                            ("FINANCE", "Finance"),
                            ("VENTES", "Ventes"),
                            ("OPERATIONS", "Opérations"),
                            ("LEGAL", "Juridique"),
                            ("MARKETING", "Marketing"),
                            ("LOGISTIQUE", "Logistique"),
                            ("QUALITE", "Qualité"),
                            ("PRODUCTION", "Production"),
                            ("ACHATS", "Achats"),
                            ("COMMUNICATION", "Communication"),
                        ],
                        help_text="Département responsable",
                        max_length=50,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONGE", "Congé"),
                            ("NOTE_FRAIS", "Note de Frais"),
                            ("RAPPORT", "Rapport"),
                            ("BUDGET", "Budget"),
                            ("CONTRAT", "Contrat"),
                            ("DEMANDE", "Demande"),
                            ("ATTESTATION", "Attestation"),
                            ("JUSTIFICATIF", "Justificatif"),
                        ],
                        help_text="Type de document disponible",
                        max_length=50,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Ce type de document est-il disponible pour ce département?",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description du type de document pour ce département",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_type_configuration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Configuration de validation des fichiers pour ce type de document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_document_types",
                        to="documents.filetypeconfiguration",
                    ),
                ),
                (
                    "target_folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dossier de destination pour ce type de document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_type_mappings",
                        to="folders.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de document par département",
                "verbose_name_plural": "Types de documents par département",
                "db_table": "department_document_types",
                "ordering": ("department", "document_type"),
                "unique_together": {("department", "document_type")},
            },
        ),
    ]
